// This file is adapted from the original ktrl's `keys.rs` file for Windows.

#[cfg(not(feature = "interception_driver"))]
use crate::oskbd::*;
use std::convert::TryFrom;

use super::{OsCode, KeyEvent, KeyValue};

#[allow(unused)]
mod keys {
    // Taken from:
    // https://github.com/retep998/winapi-rs/blob/0.3/src/um/winuser.rs#L253
    pub const VK_LBUTTON: u32 = 0x01;
    pub const VK_RBUTTON: u32 = 0x02;
    pub const VK_CANCEL: u32 = 0x03;
    pub const VK_MBUTTON: u32 = 0x04;
    pub const VK_XBUTTON1: u32 = 0x05;
    pub const VK_XBUTTON2: u32 = 0x06;
    pub const VK_BACK: u32 = 0x08;
    pub const VK_TAB: u32 = 0x09;
    pub const VK_CLEAR: u32 = 0x0C;
    pub const VK_RETURN: u32 = 0x0D;
    pub const VK_SHIFT: u32 = 0x10;
    pub const VK_CONTROL: u32 = 0x11;
    pub const VK_MENU: u32 = 0x12;
    pub const VK_PAUSE: u32 = 0x13;
    pub const VK_CAPITAL: u32 = 0x14;
    pub const VK_KANA: u32 = 0x15;
    pub const VK_HANGEUL: u32 = 0x15;
    pub const VK_HANGUL: u32 = 0x15;
    pub const VK_JUNJA: u32 = 0x17;
    pub const VK_FINAL: u32 = 0x18;
    pub const VK_HANJA: u32 = 0x19;
    pub const VK_KANJI: u32 = 0x19;
    pub const VK_ESCAPE: u32 = 0x1B;
    pub const VK_CONVERT: u32 = 0x1C;
    pub const VK_NONCONVERT: u32 = 0x1D;
    pub const VK_ACCEPT: u32 = 0x1E;
    pub const VK_MODECHANGE: u32 = 0x1F;
    pub const VK_SPACE: u32 = 0x20;
    pub const VK_PRIOR: u32 = 0x21;
    pub const VK_NEXT: u32 = 0x22;
    pub const VK_END: u32 = 0x23;
    pub const VK_HOME: u32 = 0x24;
    pub const VK_LEFT: u32 = 0x25;
    pub const VK_UP: u32 = 0x26;
    pub const VK_RIGHT: u32 = 0x27;
    pub const VK_DOWN: u32 = 0x28;
    pub const VK_SELECT: u32 = 0x29;
    pub const VK_PRINT: u32 = 0x2A;
    pub const VK_EXECUTE: u32 = 0x2B;
    pub const VK_SNAPSHOT: u32 = 0x2C;
    pub const VK_INSERT: u32 = 0x2D;
    pub const VK_DELETE: u32 = 0x2E;
    pub const VK_HELP: u32 = 0x2F;
    pub const VK_LWIN: u32 = 0x5B;
    pub const VK_RWIN: u32 = 0x5C;
    pub const VK_APPS: u32 = 0x5D;
    pub const VK_SLEEP: u32 = 0x5F;
    pub const VK_NUMPAD0: u32 = 0x60;
    pub const VK_NUMPAD1: u32 = 0x61;
    pub const VK_NUMPAD2: u32 = 0x62;
    pub const VK_NUMPAD3: u32 = 0x63;
    pub const VK_NUMPAD4: u32 = 0x64;
    pub const VK_NUMPAD5: u32 = 0x65;
    pub const VK_NUMPAD6: u32 = 0x66;
    pub const VK_NUMPAD7: u32 = 0x67;
    pub const VK_NUMPAD8: u32 = 0x68;
    pub const VK_NUMPAD9: u32 = 0x69;
    pub const VK_MULTIPLY: u32 = 0x6A;
    pub const VK_ADD: u32 = 0x6B;
    pub const VK_SEPARATOR: u32 = 0x6C;
    pub const VK_SUBTRACT: u32 = 0x6D;
    pub const VK_DECIMAL: u32 = 0x6E;
    pub const VK_DIVIDE: u32 = 0x6F;
    pub const VK_F1: u32 = 0x70;
    pub const VK_F2: u32 = 0x71;
    pub const VK_F3: u32 = 0x72;
    pub const VK_F4: u32 = 0x73;
    pub const VK_F5: u32 = 0x74;
    pub const VK_F6: u32 = 0x75;
    pub const VK_F7: u32 = 0x76;
    pub const VK_F8: u32 = 0x77;
    pub const VK_F9: u32 = 0x78;
    pub const VK_F10: u32 = 0x79;
    pub const VK_F11: u32 = 0x7A;
    pub const VK_F12: u32 = 0x7B;
    pub const VK_F13: u32 = 0x7C;
    pub const VK_F14: u32 = 0x7D;
    pub const VK_F15: u32 = 0x7E;
    pub const VK_F16: u32 = 0x7F;
    pub const VK_F17: u32 = 0x80;
    pub const VK_F18: u32 = 0x81;
    pub const VK_F19: u32 = 0x82;
    pub const VK_F20: u32 = 0x83;
    pub const VK_F21: u32 = 0x84;
    pub const VK_F22: u32 = 0x85;
    pub const VK_F23: u32 = 0x86;
    pub const VK_F24: u32 = 0x87;
    pub const VK_NAVIGATION_VIEW: u32 = 0x88;
    pub const VK_NAVIGATION_MENU: u32 = 0x89;
    pub const VK_NAVIGATION_UP: u32 = 0x8A;
    pub const VK_NAVIGATION_DOWN: u32 = 0x8B;
    pub const VK_NAVIGATION_LEFT: u32 = 0x8C;
    pub const VK_NAVIGATION_RIGHT: u32 = 0x8D;
    pub const VK_NAVIGATION_ACCEPT: u32 = 0x8E;
    pub const VK_NAVIGATION_CANCEL: u32 = 0x8F;
    pub const VK_NUMLOCK: u32 = 0x90;
    pub const VK_SCROLL: u32 = 0x91;
    pub const VK_OEM_NEC_EQUAL: u32 = 0x92;
    pub const VK_OEM_FJ_JISHO: u32 = 0x92;
    pub const VK_OEM_FJ_MASSHOU: u32 = 0x93;
    pub const VK_OEM_FJ_TOUROKU: u32 = 0x94;
    pub const VK_OEM_FJ_LOYA: u32 = 0x95;
    pub const VK_OEM_FJ_ROYA: u32 = 0x96;
    pub const VK_LSHIFT: u32 = 0xA0;
    pub const VK_RSHIFT: u32 = 0xA1;
    pub const VK_LCONTROL: u32 = 0xA2;
    pub const VK_RCONTROL: u32 = 0xA3;
    pub const VK_LMENU: u32 = 0xA4;
    pub const VK_RMENU: u32 = 0xA5;
    pub const VK_BROWSER_BACK: u32 = 0xA6;
    pub const VK_BROWSER_FORWARD: u32 = 0xA7;
    pub const VK_BROWSER_REFRESH: u32 = 0xA8;
    pub const VK_BROWSER_STOP: u32 = 0xA9;
    pub const VK_BROWSER_SEARCH: u32 = 0xAA;
    pub const VK_BROWSER_FAVORITES: u32 = 0xAB;
    pub const VK_BROWSER_HOME: u32 = 0xAC;
    pub const VK_VOLUME_MUTE: u32 = 0xAD;
    pub const VK_VOLUME_DOWN: u32 = 0xAE;
    pub const VK_VOLUME_UP: u32 = 0xAF;
    pub const VK_MEDIA_NEXT_TRACK: u32 = 0xB0;
    pub const VK_MEDIA_PREV_TRACK: u32 = 0xB1;
    pub const VK_MEDIA_STOP: u32 = 0xB2;
    pub const VK_MEDIA_PLAY_PAUSE: u32 = 0xB3;
    pub const VK_LAUNCH_MAIL: u32 = 0xB4;
    pub const VK_LAUNCH_MEDIA_SELECT: u32 = 0xB5;
    pub const VK_LAUNCH_APP1: u32 = 0xB6;
    pub const VK_LAUNCH_APP2: u32 = 0xB7;
    pub const VK_OEM_1: u32 = 0xBA;
    pub const VK_OEM_PLUS: u32 = 0xBB;
    pub const VK_OEM_COMMA: u32 = 0xBC;
    pub const VK_OEM_MINUS: u32 = 0xBD;
    pub const VK_OEM_PERIOD: u32 = 0xBE;
    pub const VK_OEM_2: u32 = 0xBF;
    pub const VK_OEM_3: u32 = 0xC0;
    pub const VK_GAMEPAD_A: u32 = 0xC3;
    pub const VK_GAMEPAD_B: u32 = 0xC4;
    pub const VK_GAMEPAD_X: u32 = 0xC5;
    pub const VK_GAMEPAD_Y: u32 = 0xC6;
    pub const VK_GAMEPAD_RIGHT_SHOULDER: u32 = 0xC7;
    pub const VK_GAMEPAD_LEFT_SHOULDER: u32 = 0xC8;
    pub const VK_GAMEPAD_LEFT_TRIGGER: u32 = 0xC9;
    pub const VK_GAMEPAD_RIGHT_TRIGGER: u32 = 0xCA;
    pub const VK_GAMEPAD_DPAD_UP: u32 = 0xCB;
    pub const VK_GAMEPAD_DPAD_DOWN: u32 = 0xCC;
    pub const VK_GAMEPAD_DPAD_LEFT: u32 = 0xCD;
    pub const VK_GAMEPAD_DPAD_RIGHT: u32 = 0xCE;
    pub const VK_GAMEPAD_MENU: u32 = 0xCF;
    pub const VK_GAMEPAD_VIEW: u32 = 0xD0;
    pub const VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON: u32 = 0xD1;
    pub const VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON: u32 = 0xD2;
    pub const VK_GAMEPAD_LEFT_THUMBSTICK_UP: u32 = 0xD3;
    pub const VK_GAMEPAD_LEFT_THUMBSTICK_DOWN: u32 = 0xD4;
    pub const VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT: u32 = 0xD5;
    pub const VK_GAMEPAD_LEFT_THUMBSTICK_LEFT: u32 = 0xD6;
    pub const VK_GAMEPAD_RIGHT_THUMBSTICK_UP: u32 = 0xD7;
    pub const VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN: u32 = 0xD8;
    pub const VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT: u32 = 0xD9;
    pub const VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT: u32 = 0xDA;
    pub const VK_OEM_4: u32 = 0xDB;
    pub const VK_OEM_5: u32 = 0xDC;
    pub const VK_OEM_6: u32 = 0xDD;
    pub const VK_OEM_7: u32 = 0xDE;
    pub const VK_OEM_8: u32 = 0xDF;
    pub const VK_OEM_AX: u32 = 0xE1;
    pub const VK_OEM_102: u32 = 0xE2;
    pub const VK_ICO_HELP: u32 = 0xE3;
    pub const VK_ICO_00: u32 = 0xE4;
    pub const VK_PROCESSKEY: u32 = 0xE5;
    pub const VK_ICO_CLEAR: u32 = 0xE6;
    pub const VK_PACKET: u32 = 0xE7;
    pub const VK_OEM_RESET: u32 = 0xE9;
    pub const VK_OEM_JUMP: u32 = 0xEA;
    pub const VK_OEM_PA1: u32 = 0xEB;
    pub const VK_OEM_PA2: u32 = 0xEC;
    pub const VK_OEM_PA3: u32 = 0xED;
    pub const VK_OEM_WSCTRL: u32 = 0xEE;
    pub const VK_OEM_CUSEL: u32 = 0xEF;
    pub const VK_OEM_ATTN: u32 = 0xF0;
    pub const VK_OEM_FINISH: u32 = 0xF1;
    pub const VK_OEM_COPY: u32 = 0xF2;
    pub const VK_OEM_AUTO: u32 = 0xF3;
    pub const VK_OEM_ENLW: u32 = 0xF4;
    pub const VK_OEM_BACKTAB: u32 = 0xF5;
    pub const VK_ATTN: u32 = 0xF6;
    pub const VK_CRSEL: u32 = 0xF7;
    pub const VK_EXSEL: u32 = 0xF8;
    pub const VK_EREOF: u32 = 0xF9;
    pub const VK_PLAY: u32 = 0xFA;
    pub const VK_ZOOM: u32 = 0xFB;
    pub const VK_NONAME: u32 = 0xFC;
    pub const VK_PA1: u32 = 0xFD;
    pub const VK_OEM_CLEAR: u32 = 0xFE;
}
pub use keys::*;

impl OsCode {
    pub fn from_u32(code: u32) -> Option<Self> {
        match code {
            0x30 => Some(OsCode::KEY_0),
            0x31 => Some(OsCode::KEY_1),
            0x32 => Some(OsCode::KEY_2),
            0x33 => Some(OsCode::KEY_3),
            0x34 => Some(OsCode::KEY_4),
            0x35 => Some(OsCode::KEY_5),
            0x36 => Some(OsCode::KEY_6),
            0x37 => Some(OsCode::KEY_7),
            0x38 => Some(OsCode::KEY_8),
            0x39 => Some(OsCode::KEY_9),
            0x41 => Some(OsCode::KEY_A),
            0x42 => Some(OsCode::KEY_B),
            0x43 => Some(OsCode::KEY_C),
            0x44 => Some(OsCode::KEY_D),
            0x45 => Some(OsCode::KEY_E),
            0x46 => Some(OsCode::KEY_F),
            0x47 => Some(OsCode::KEY_G),
            0x48 => Some(OsCode::KEY_H),
            0x49 => Some(OsCode::KEY_I),
            0x4A => Some(OsCode::KEY_J),
            0x4B => Some(OsCode::KEY_K),
            0x4C => Some(OsCode::KEY_L),
            0x4D => Some(OsCode::KEY_M),
            0x4E => Some(OsCode::KEY_N),
            0x4F => Some(OsCode::KEY_O),
            0x50 => Some(OsCode::KEY_P),
            0x51 => Some(OsCode::KEY_Q),
            0x52 => Some(OsCode::KEY_R),
            0x53 => Some(OsCode::KEY_S),
            0x54 => Some(OsCode::KEY_T),
            0x55 => Some(OsCode::KEY_U),
            0x56 => Some(OsCode::KEY_V),
            0x57 => Some(OsCode::KEY_W),
            0x58 => Some(OsCode::KEY_X),
            0x59 => Some(OsCode::KEY_Y),
            0x5A => Some(OsCode::KEY_Z),
            VK_OEM_1 => Some(OsCode::KEY_SEMICOLON),
            VK_OEM_2 => Some(OsCode::KEY_SLASH),
            VK_OEM_3 => Some(OsCode::KEY_GRAVE),
            VK_OEM_4 => Some(OsCode::KEY_LEFTBRACE),
            VK_OEM_5 => Some(OsCode::KEY_BACKSLASH),
            VK_OEM_6 => Some(OsCode::KEY_RIGHTBRACE),
            VK_OEM_7 => Some(OsCode::KEY_APOSTROPHE),
            VK_OEM_MINUS => Some(OsCode::KEY_MINUS),
            VK_OEM_PERIOD => Some(OsCode::KEY_DOT),
            VK_OEM_PLUS => Some(OsCode::KEY_EQUAL),
            VK_BACK => Some(OsCode::KEY_BACKSPACE),
            VK_ESCAPE => Some(OsCode::KEY_ESC),
            VK_TAB => Some(OsCode::KEY_TAB),
            VK_RETURN => Some(OsCode::KEY_ENTER),
            VK_LCONTROL => Some(OsCode::KEY_LEFTCTRL),
            VK_LSHIFT => Some(OsCode::KEY_LEFTSHIFT),
            VK_OEM_COMMA => Some(OsCode::KEY_COMMA),
            VK_RSHIFT => Some(OsCode::KEY_RIGHTSHIFT),
            VK_MULTIPLY => Some(OsCode::KEY_KPASTERISK),
            VK_LMENU => Some(OsCode::KEY_LEFTALT),
            VK_SPACE => Some(OsCode::KEY_SPACE),
            VK_CAPITAL => Some(OsCode::KEY_CAPSLOCK),
            VK_F1 => Some(OsCode::KEY_F1),
            VK_F2 => Some(OsCode::KEY_F2),
            VK_F3 => Some(OsCode::KEY_F3),
            VK_F4 => Some(OsCode::KEY_F4),
            VK_F5 => Some(OsCode::KEY_F5),
            VK_F6 => Some(OsCode::KEY_F6),
            VK_F7 => Some(OsCode::KEY_F7),
            VK_F8 => Some(OsCode::KEY_F8),
            VK_F9 => Some(OsCode::KEY_F9),
            VK_F10 => Some(OsCode::KEY_F10),
            VK_F11 => Some(OsCode::KEY_F11),
            VK_F12 => Some(OsCode::KEY_F12),
            VK_NUMLOCK => Some(OsCode::KEY_NUMLOCK),
            VK_CLEAR => Some(OsCode::KEY_CLEAR),
            VK_SCROLL => Some(OsCode::KEY_SCROLLLOCK),
            VK_NUMPAD0 => Some(OsCode::KEY_KP0),
            VK_NUMPAD1 => Some(OsCode::KEY_KP1),
            VK_NUMPAD2 => Some(OsCode::KEY_KP2),
            VK_NUMPAD3 => Some(OsCode::KEY_KP3),
            VK_NUMPAD4 => Some(OsCode::KEY_KP4),
            VK_NUMPAD5 => Some(OsCode::KEY_KP5),
            VK_NUMPAD6 => Some(OsCode::KEY_KP6),
            VK_NUMPAD7 => Some(OsCode::KEY_KP7),
            VK_NUMPAD8 => Some(OsCode::KEY_KP8),
            VK_NUMPAD9 => Some(OsCode::KEY_KP9),
            VK_SUBTRACT => Some(OsCode::KEY_KPMINUS),
            VK_ADD => Some(OsCode::KEY_KPPLUS),
            VK_DECIMAL => Some(OsCode::KEY_KPDOT),
            VK_RCONTROL => Some(OsCode::KEY_RIGHTCTRL),
            VK_DIVIDE => Some(OsCode::KEY_KPSLASH),
            VK_RMENU => Some(OsCode::KEY_RIGHTALT),
            VK_HOME => Some(OsCode::KEY_HOME),
            VK_UP => Some(OsCode::KEY_UP),
            VK_PRIOR => Some(OsCode::KEY_PAGEUP),
            VK_LEFT => Some(OsCode::KEY_LEFT),
            VK_RIGHT => Some(OsCode::KEY_RIGHT),
            VK_END => Some(OsCode::KEY_END),
            VK_DOWN => Some(OsCode::KEY_DOWN),
            VK_NEXT => Some(OsCode::KEY_PAGEDOWN),
            VK_INSERT => Some(OsCode::KEY_INSERT),
            VK_DELETE => Some(OsCode::KEY_DELETE),
            VK_VOLUME_MUTE => Some(OsCode::KEY_MUTE),
            VK_VOLUME_DOWN => Some(OsCode::KEY_VOLUMEDOWN),
            VK_VOLUME_UP => Some(OsCode::KEY_VOLUMEUP),
            VK_PAUSE => Some(OsCode::KEY_PAUSE),
            VK_LWIN => Some(OsCode::KEY_LEFTMETA),
            VK_RWIN => Some(OsCode::KEY_RIGHTMETA),
            VK_APPS => Some(OsCode::KEY_COMPOSE),
            VK_BROWSER_BACK => Some(OsCode::KEY_BACK),
            VK_BROWSER_FORWARD => Some(OsCode::KEY_FORWARD),
            VK_MEDIA_NEXT_TRACK => Some(OsCode::KEY_NEXTSONG),
            VK_MEDIA_PLAY_PAUSE => Some(OsCode::KEY_PLAYPAUSE),
            VK_MEDIA_PREV_TRACK => Some(OsCode::KEY_PREVIOUSSONG),
            VK_MEDIA_STOP => Some(OsCode::KEY_STOP),
            VK_BROWSER_HOME => Some(OsCode::KEY_HOMEPAGE),
            VK_BROWSER_REFRESH => Some(OsCode::KEY_REFRESH),
            VK_F13 => Some(OsCode::KEY_F13),
            VK_F14 => Some(OsCode::KEY_F14),
            VK_F15 => Some(OsCode::KEY_F15),
            VK_F16 => Some(OsCode::KEY_F16),
            VK_F17 => Some(OsCode::KEY_F17),
            VK_F18 => Some(OsCode::KEY_F18),
            VK_F19 => Some(OsCode::KEY_F19),
            VK_F20 => Some(OsCode::KEY_F20),
            VK_F21 => Some(OsCode::KEY_F21),
            VK_F22 => Some(OsCode::KEY_F22),
            VK_F23 => Some(OsCode::KEY_F23),
            VK_F24 => Some(OsCode::KEY_F24),
            VK_HANGEUL => Some(OsCode::KEY_HANGEUL),
            VK_HANJA => Some(OsCode::KEY_HANJA),
            VK_OEM_102 => Some(OsCode::KEY_102ND),
            VK_PLAY => Some(OsCode::KEY_PLAY),
            VK_SNAPSHOT => Some(OsCode::KEY_PRINT),
            VK_BROWSER_SEARCH => Some(OsCode::KEY_SEARCH),
            VK_BROWSER_FAVORITES => Some(OsCode::KEY_FAVORITES),
            0xC1 => Some(OsCode::KEY_RO),
            _ => None,
        }
    }

    pub fn as_u32(self) -> u32 {
        match self {
            OsCode::KEY_0 => 0x30,
            OsCode::KEY_1 => 0x31,
            OsCode::KEY_2 => 0x32,
            OsCode::KEY_3 => 0x33,
            OsCode::KEY_4 => 0x34,
            OsCode::KEY_5 => 0x35,
            OsCode::KEY_6 => 0x36,
            OsCode::KEY_7 => 0x37,
            OsCode::KEY_8 => 0x38,
            OsCode::KEY_9 => 0x39,
            OsCode::KEY_A => 0x41,
            OsCode::KEY_B => 0x42,
            OsCode::KEY_C => 0x43,
            OsCode::KEY_D => 0x44,
            OsCode::KEY_E => 0x45,
            OsCode::KEY_F => 0x46,
            OsCode::KEY_G => 0x47,
            OsCode::KEY_H => 0x48,
            OsCode::KEY_I => 0x49,
            OsCode::KEY_J => 0x4A,
            OsCode::KEY_K => 0x4B,
            OsCode::KEY_L => 0x4C,
            OsCode::KEY_M => 0x4D,
            OsCode::KEY_N => 0x4E,
            OsCode::KEY_O => 0x4F,
            OsCode::KEY_P => 0x50,
            OsCode::KEY_Q => 0x51,
            OsCode::KEY_R => 0x52,
            OsCode::KEY_S => 0x53,
            OsCode::KEY_T => 0x54,
            OsCode::KEY_U => 0x55,
            OsCode::KEY_V => 0x56,
            OsCode::KEY_W => 0x57,
            OsCode::KEY_X => 0x58,
            OsCode::KEY_Y => 0x59,
            OsCode::KEY_Z => 0x5A,
            OsCode::KEY_SEMICOLON => VK_OEM_1,
            OsCode::KEY_SLASH => VK_OEM_2,
            OsCode::KEY_GRAVE => VK_OEM_3,
            OsCode::KEY_LEFTBRACE => VK_OEM_4,
            OsCode::KEY_BACKSLASH => VK_OEM_5,
            OsCode::KEY_RIGHTBRACE => VK_OEM_6,
            OsCode::KEY_APOSTROPHE => VK_OEM_7,
            OsCode::KEY_MINUS => VK_OEM_MINUS,
            OsCode::KEY_DOT => VK_OEM_PERIOD,
            OsCode::KEY_EQUAL => VK_OEM_PLUS,
            OsCode::KEY_BACKSPACE => VK_BACK,
            OsCode::KEY_ESC => VK_ESCAPE,
            OsCode::KEY_TAB => VK_TAB,
            OsCode::KEY_ENTER => VK_RETURN,
            OsCode::KEY_LEFTCTRL => VK_LCONTROL,
            OsCode::KEY_LEFTSHIFT => VK_LSHIFT,
            OsCode::KEY_COMMA => VK_OEM_COMMA,
            OsCode::KEY_RIGHTSHIFT => VK_RSHIFT,
            OsCode::KEY_KPASTERISK => VK_MULTIPLY,
            OsCode::KEY_LEFTALT => VK_LMENU,
            OsCode::KEY_SPACE => VK_SPACE,
            OsCode::KEY_CAPSLOCK => VK_CAPITAL,
            OsCode::KEY_F1 => VK_F1,
            OsCode::KEY_F2 => VK_F2,
            OsCode::KEY_F3 => VK_F3,
            OsCode::KEY_F4 => VK_F4,
            OsCode::KEY_F5 => VK_F5,
            OsCode::KEY_F6 => VK_F6,
            OsCode::KEY_F7 => VK_F7,
            OsCode::KEY_F8 => VK_F8,
            OsCode::KEY_F9 => VK_F9,
            OsCode::KEY_F10 => VK_F10,
            OsCode::KEY_F11 => VK_F11,
            OsCode::KEY_F12 => VK_F12,
            OsCode::KEY_NUMLOCK => VK_NUMLOCK,
            OsCode::KEY_CLEAR => VK_CLEAR,
            OsCode::KEY_SCROLLLOCK => VK_SCROLL,
            OsCode::KEY_KP0 => VK_NUMPAD0,
            OsCode::KEY_KP1 => VK_NUMPAD1,
            OsCode::KEY_KP2 => VK_NUMPAD2,
            OsCode::KEY_KP3 => VK_NUMPAD3,
            OsCode::KEY_KP4 => VK_NUMPAD4,
            OsCode::KEY_KP5 => VK_NUMPAD5,
            OsCode::KEY_KP6 => VK_NUMPAD6,
            OsCode::KEY_KP7 => VK_NUMPAD7,
            OsCode::KEY_KP8 => VK_NUMPAD8,
            OsCode::KEY_KP9 => VK_NUMPAD9,
            OsCode::KEY_KPMINUS => VK_SUBTRACT,
            OsCode::KEY_KPPLUS => VK_ADD,
            OsCode::KEY_KPDOT => VK_DECIMAL,
            OsCode::KEY_RIGHTCTRL => VK_RCONTROL,
            OsCode::KEY_KPSLASH => VK_DIVIDE,
            OsCode::KEY_RIGHTALT => VK_RMENU,
            OsCode::KEY_HOME => VK_HOME,
            OsCode::KEY_UP => VK_UP,
            OsCode::KEY_PAGEUP => VK_PRIOR,
            OsCode::KEY_LEFT => VK_LEFT,
            OsCode::KEY_RIGHT => VK_RIGHT,
            OsCode::KEY_END => VK_END,
            OsCode::KEY_DOWN => VK_DOWN,
            OsCode::KEY_PAGEDOWN => VK_NEXT,
            OsCode::KEY_INSERT => VK_INSERT,
            OsCode::KEY_DELETE => VK_DELETE,
            OsCode::KEY_MUTE => VK_VOLUME_MUTE,
            OsCode::KEY_VOLUMEDOWN => VK_VOLUME_DOWN,
            OsCode::KEY_VOLUMEUP => VK_VOLUME_UP,
            OsCode::KEY_PAUSE => VK_PAUSE,
            OsCode::KEY_LEFTMETA => VK_LWIN,
            OsCode::KEY_RIGHTMETA => VK_RWIN,
            OsCode::KEY_COMPOSE => VK_APPS,
            OsCode::KEY_BACK => VK_BROWSER_BACK,
            OsCode::KEY_FORWARD => VK_BROWSER_FORWARD,
            OsCode::KEY_NEXTSONG => VK_MEDIA_NEXT_TRACK,
            OsCode::KEY_PLAYPAUSE => VK_MEDIA_PLAY_PAUSE,
            OsCode::KEY_PREVIOUSSONG => VK_MEDIA_PREV_TRACK,
            OsCode::KEY_STOP => VK_MEDIA_STOP,
            OsCode::KEY_HOMEPAGE => VK_BROWSER_HOME,
            OsCode::KEY_REFRESH => VK_BROWSER_REFRESH,
            OsCode::KEY_F13 => VK_F13,
            OsCode::KEY_F14 => VK_F14,
            OsCode::KEY_F15 => VK_F15,
            OsCode::KEY_F16 => VK_F16,
            OsCode::KEY_F17 => VK_F17,
            OsCode::KEY_F18 => VK_F18,
            OsCode::KEY_F19 => VK_F19,
            OsCode::KEY_F20 => VK_F20,
            OsCode::KEY_F21 => VK_F21,
            OsCode::KEY_F22 => VK_F22,
            OsCode::KEY_F23 => VK_F23,
            OsCode::KEY_F24 => VK_F24,
            OsCode::KEY_HANGEUL => VK_HANGEUL,
            OsCode::KEY_HANJA => VK_HANJA,
            OsCode::KEY_102ND => VK_OEM_102,
            OsCode::KEY_PLAY => VK_PLAY,
            OsCode::KEY_PRINT => VK_SNAPSHOT,
            OsCode::KEY_SEARCH => VK_BROWSER_SEARCH,
            OsCode::KEY_FAVORITES => VK_BROWSER_FAVORITES,
            OsCode::KEY_RO => 0xC1,
            _ => 0,
        }
    }
}

#[cfg(not(feature = "interception_driver"))]
impl TryFrom<InputEvent> for KeyEvent {
    type Error = ();
    fn try_from(item: InputEvent) -> Result<Self, Self::Error> {
        Ok(Self {
            code: OsCode::from_u32(item.code as u32).ok_or(())?,
            value: match item.up {
                true => KeyValue::Release,
                false => KeyValue::Press,
            },
        })
    }
}

#[cfg(not(feature = "interception_driver"))]
impl From<KeyEvent> for InputEvent {
    fn from(item: KeyEvent) -> Self {
        Self {
            code: item.code.into(),
            up: item.value.into(),
        }
    }
}
