name: "Bug report"
description: Create a report to help us improve.
labels: ["bug"]
assignees: ["jtroo"]
title: "Bug: title_goes_here"
body:
  - type: checkboxes
    attributes:
      label: Requirements
      description: Before you create a bug report, please check the following
      options:
        - label: I've searched [platform-specific issues](https://github.com/jtroo/kanata/blob/main/docs/platform-known-issues.adoc), [issues](https://github.com/jtroo/kanata/issues) and [discussions](https://github.com/jtroo/kanata/discussions) to see if this has been reported before.
          required: true
        - label: My issue does not involve multiple simultaneous key presses, OR it does but I've confirmed it is not [key rollover or ghosting](https://github.com/jtroo/kanata/discussions/822).
          required: true
  - type: textarea
    id: summary
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Relevant kanata config
      description: E.g. defcfg, defsrc, deflayer, defalias items. If in doubt, feel free to include your entire config. Please ensure to use code formatting, e.g. surround with triple backticks to avoid pinging users with the @ character.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: |
        Walk us through the steps needed to reproduce the bug.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Kanata version
      description: The kanata version prints in the log on startup, or you can also print it by passing the `--version` flag when running on the command line.
      placeholder: e.g. kanata 1.3.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Debug logs
      description: If you think it might help with a non-obvious issue, run kanata from the command line and pass the `--debug` flag. This will print more info. Include the relevant log outputs this section if you did so.
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating system
      description: Linux or Windows?
      placeholder: e.g. Windows 11
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
